name: EcoSentinel
description: A Flutter application for environmental governance, providing tools for monitoring and reporting environmental issues.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Routing
  auto_route: ^10.1.0+1
  go_router: ^16.0.0

  # State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^3.15.1
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.3.9
  firebase_messaging: ^15.2.9

  # HTTP & API
  dio: ^5.4.3
  retrofit: ^4.1.0
  json_annotation: ^4.9.0

  # Local Storage
  sqflite: ^2.3.3
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Device & Info
  device_info_plus: ^11.5.0
  package_info_plus: ^8.3.0
  permission_handler: ^12.0.1
  connectivity_plus: ^6.1.4
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  location: ^8.0.1

  # UI & Design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_maps_flutter: ^2.5.3

  # Camera & Media
  camera: ^0.11.1
  image_picker: ^1.1.2
  video_player: ^2.8.6
  file_picker: ^8.1.2
  lottie: ^3.3.1
  fl_chart: ^1.0.0

  # Charts & Data Visualization
  charts_flutter_new: ^0.12.0

  # Voice & Audio
  speech_to_text: ^7.1.0
  flutter_tts: ^4.2.3
  audio_waveforms: ^1.0.5

  # Utilities
  email_validator: ^3.0.0
  share_plus: ^11.0.0
  url_launcher: ^6.3.0
  timeago: ^3.6.1
  crypto: ^3.0.3
  workmanager: ^0.8.0

  # Notifications
  flutter_local_notifications: ^19.3.0

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.9.5
  retrofit_generator: ^9.3.0

  # Testing
  bloc_test: ^10.0.0
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter

  # Code Quality
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # Fonts - uncomment when you add font files
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  output_localization_file: app_localizations.dart
  output_class: AppLocalizations

# Fix for intl version conflicts between flutter_localizations and other packages
dependency_overrides:
  intl: ^0.20.2